export const VERBS=[
  {k:"買う",r:"かう",m:"to buy",t:"g"},{k:"会う",r:"あう",m:"to meet",t:"g"},{k:"使う",r:"つかう",m:"to use",t:"g"},
  {k:"歌う",r:"うたう",m:"to sing",t:"g"},{k:"洗う",r:"あらう",m:"to wash",t:"g"},{k:"習う",r:"ならう",m:"to learn",t:"g"},
  {k:"行く",r:"いく",m:"to go",t:"g",x:1},{k:"書く",r:"かく",m:"to write",t:"g"},{k:"聞く",r:"きく",m:"to listen",t:"g"},
  {k:"歩く",r:"あるく",m:"to walk",t:"g"},{k:"働く",r:"はたらく",m:"to work",t:"g"},
  {k:"泳ぐ",r:"およぐ",m:"to swim",t:"g"},{k:"急ぐ",r:"いそぐ",m:"to hurry",t:"g"},{k:"脱ぐ",r:"ぬぐ",m:"to take off",t:"g"},
  {k:"話す",r:"はなす",m:"to speak",t:"g"},{k:"貸す",r:"かす",m:"to lend",t:"g"},{k:"消す",r:"けす",m:"to turn off",t:"g"},
  {k:"待つ",r:"まつ",m:"to wait",t:"g"},{k:"持つ",r:"もつ",m:"to hold",t:"g"},{k:"立つ",r:"たつ",m:"to stand",t:"g"},
  {k:"死ぬ",r:"しぬ",m:"to die",t:"g"},
  {k:"遊ぶ",r:"あそぶ",m:"to play",t:"g"},{k:"呼ぶ",r:"よぶ",m:"to call",t:"g"},{k:"飛ぶ",r:"とぶ",m:"to fly",t:"g"},
  {k:"飲む",r:"のむ",m:"to drink",t:"g"},{k:"読む",r:"よむ",m:"to read",t:"g"},{k:"休む",r:"やすむ",m:"to rest",t:"g"},
  {k:"住む",r:"すむ",m:"to live (in)",t:"g"},
  {k:"帰る",r:"かえる",m:"to go home ⚠godan",t:"g"},{k:"入る",r:"はいる",m:"to enter ⚠godan",t:"g"},
  {k:"走る",r:"はしる",m:"to run ⚠godan",t:"g"},{k:"知る",r:"しる",m:"to know ⚠godan",t:"g"},
  {k:"切る",r:"きる",m:"to cut ⚠godan",t:"g"},{k:"作る",r:"つくる",m:"to make",t:"g"},
  {k:"乗る",r:"のる",m:"to ride",t:"g"},{k:"取る",r:"とる",m:"to take",t:"g"},{k:"売る",r:"うる",m:"to sell",t:"g"},
  {k:"送る",r:"おくる",m:"to send",t:"g"},{k:"座る",r:"すわる",m:"to sit",t:"g"},
  {k:"食べる",r:"たべる",m:"to eat",t:"i"},{k:"見る",r:"みる",m:"to see",t:"i"},{k:"寝る",r:"ねる",m:"to sleep",t:"i"},
  {k:"起きる",r:"おきる",m:"to wake up",t:"i"},{k:"出る",r:"でる",m:"to leave",t:"i"},
  {k:"開ける",r:"あける",m:"to open",t:"i"},{k:"閉める",r:"しめる",m:"to close",t:"i"},
  {k:"教える",r:"おしえる",m:"to teach",t:"i"},{k:"覚える",r:"おぼえる",m:"to memorize",t:"i"},
  {k:"忘れる",r:"わすれる",m:"to forget",t:"i"},{k:"借りる",r:"かりる",m:"to borrow",t:"i"},
  {k:"着る",r:"きる",m:"to wear",t:"i"},{k:"降りる",r:"おりる",m:"to get off",t:"i"},{k:"浴びる",r:"あびる",m:"to shower",t:"i"},
  {k:"する",r:"する",m:"to do",t:"s"},{k:"勉強する",r:"べんきょうする",m:"to study",t:"s"},
  {k:"電話する",r:"でんわする",m:"to phone",t:"s"},{k:"掃除する",r:"そうじする",m:"to clean",t:"s"},
  {k:"練習する",r:"れんしゅうする",m:"to practice",t:"s"},{k:"来る",r:"くる",m:"to come",t:"k"}
];
export const ADJS=[
  {k:"高い",r:"たかい",m:"tall / expensive",t:"ia"},{k:"安い",r:"やすい",m:"cheap",t:"ia"},
  {k:"大きい",r:"おおきい",m:"big",t:"ia"},{k:"小さい",r:"ちいさい",m:"small",t:"ia"},
  {k:"新しい",r:"あたらしい",m:"new",t:"ia"},{k:"古い",r:"ふるい",m:"old",t:"ia"},
  {k:"暑い",r:"あつい",m:"hot",t:"ia"},{k:"寒い",r:"さむい",m:"cold",t:"ia"},
  {k:"楽しい",r:"たのしい",m:"fun",t:"ia"},{k:"難しい",r:"むずかしい",m:"difficult",t:"ia"},
  {k:"忙しい",r:"いそがしい",m:"busy",t:"ia"},{k:"早い",r:"はやい",m:"early / fast",t:"ia"},
  {k:"近い",r:"ちかい",m:"near",t:"ia"},{k:"遠い",r:"とおい",m:"far",t:"ia"},
  {k:"おいしい",r:"おいしい",m:"delicious",t:"ia"},{k:"面白い",r:"おもしろい",m:"interesting",t:"ia"},
  {k:"いい",r:"いい",m:"good ⚠irregular",t:"ia"},
  {k:"元気",r:"げんき",m:"healthy / lively",t:"na"},{k:"静か",r:"しずか",m:"quiet",t:"na"},
  {k:"有名",r:"ゆうめい",m:"famous",t:"na"},{k:"便利",r:"べんり",m:"convenient",t:"na"},
  {k:"大変",r:"たいへん",m:"tough",t:"na"},{k:"好き",r:"すき",m:"liked",t:"na"},
  {k:"簡単",r:"かんたん",m:"simple",t:"na"},{k:"親切",r:"しんせつ",m:"kind",t:"na"},
  {k:"暇",r:"ひま",m:"free (time)",t:"na"},{k:"きれい",r:"きれい",m:"pretty / clean ⚠na-adj!",t:"na"}
];
export const FORMS=[
  {id:"te",  kind:"v", jp:"て形", en:"te-form", lvl:"N5",
   rule:"Godan: 〜う・つ・る → って ／ 〜む・ぶ・ぬ → んで ／ 〜く → いて ／ 〜ぐ → いで ／ 〜す → して\nIchidan: drop る → て\nする → して ／ くる → きて ／ ⚠ 行く → 行って"},
  {id:"ta",  kind:"v", jp:"た形", en:"plain past", lvl:"N5",
   rule:"Exactly the same sound changes as て形, with た／だ instead:\nって→った, んで→んだ, いて→いた, いで→いだ, して→した.\nIf you know て形, you know た形."},
  {id:"nai", kind:"v", jp:"ない形", en:"plain negative", lvl:"N5",
   rule:"Godan: change the last kana to the あ-row +ない (⚠ う → わ: 買う→買わない)\nIchidan: drop る + ない\nする → しない ／ くる → こない"},
  {id:"masu",kind:"v", jp:"ます形", en:"polite", lvl:"N5",
   rule:"Godan: change the last kana to the い-row + ます (飲む→飲みます)\nIchidan: drop る + ます\nする → します ／ くる → きます"},
  {id:"tai", kind:"v", jp:"たい形", en:"want to", lvl:"N5",
   rule:"Take the ます-stem and add たい.\n飲む→飲みたい ／ 食べる→食べたい ／ する→したい"},
  {id:"pot", kind:"v", jp:"可能形", en:"potential (can)", lvl:"N4",
   rule:"Godan: last kana to the え-row + る (飲む→飲める)\nIchidan: drop る + られる (⚠ 食べれる is the famous ら抜き mistake)\nする → できる ／ くる → こられる"},
  {id:"vol", kind:"v", jp:"意向形", en:"volitional (let's)", lvl:"N4",
   rule:"Godan: last kana to the お-row + う (飲む→飲もう)\nIchidan: drop る + よう\nする → しよう ／ くる → こよう"},
  {id:"ba",  kind:"v", jp:"ば形", en:"conditional 〜ば", lvl:"N4",
   rule:"Godan: last kana to the え-row + ば (飲む→飲めば)\nIchidan: drop る + れば\nする → すれば ／ くる → くれば"},
  {id:"tara",kind:"v", jp:"たら形", en:"conditional 〜たら", lvl:"N4",
   rule:"Just the た形 + ら. If you know た形, this is free.\n飲む→飲んだら ／ 食べる→食べたら ／ 行く→行ったら"},
  {id:"imp", kind:"v", jp:"命令形", en:"imperative", lvl:"N4",
   rule:"Godan: last kana to the え-row (飲む→飲め)\nIchidan: drop る + ろ (食べろ)\nする → しろ ／ くる → こい"},
  {id:"pass",kind:"v", jp:"受身形", en:"passive", lvl:"N4",
   rule:"Godan: last kana to the あ-row + れる (飲む→飲まれる)\nIchidan: drop る + られる (same as potential!)\nする → される ／ くる → こられる"},
  {id:"caus",kind:"v", jp:"使役形", en:"causative (make/let)", lvl:"N4",
   rule:"Godan: last kana to the あ-row + せる (飲む→飲ませる)\nIchidan: drop る + させる\nする → させる ／ くる → こさせる"},
  {id:"aneg", kind:"a", jp:"形容詞・否定", en:"adj negative", lvl:"N5",
   rule:"い-adj: drop い + くない (高い→高くない) ⚠ いい→よくない\nな-adj: + じゃない (静か→静かじゃない)\n⚠ きれい ends in い but is a な-adjective!"},
  {id:"apast",kind:"a", jp:"形容詞・過去", en:"adj past", lvl:"N5",
   rule:"い-adj: drop い + かった (高い→高かった) ⚠ いい→よかった\nな-adj: + だった (静か→静かだった)"},
  {id:"apneg",kind:"a", jp:"形容詞・過去否定", en:"adj past negative", lvl:"N5",
   rule:"い-adj: drop い + くなかった\nな-adj: + じゃなかった"},
  {id:"ate", kind:"a", jp:"形容詞・て形", en:"adj te-form (linking)", lvl:"N5",
   rule:"い-adj: drop い + くて (高くて安い = tall and cheap) ⚠ いい→よくて\nな-adj: + で (静かで便利 = quiet and convenient)"},
  {id:"aadv",kind:"a", jp:"副詞化", en:"adj → adverb", lvl:"N5", iaOnly:true,
   rule:"い-adj: drop い + く (早い→早く走る = run fast)\n(ない-adj use に: 静かに — not drilled here)"},
  {id:"dict", kind:"v", jp:"辞書形", en:"dictionary form", lvl:"N5",
   rule:"This is the plain, neutral form of the verb as found in a dictionary. No changes."},
  {id:"apres", kind:"a", jp:"形容詞・現在肯定", en:"adj present", lvl:"N5",
   rule:"Plain present affirmative adjective. No changes."}
];
export const FORM = Object.fromEntries(FORMS.map(f=>[f.id,f]));
export const SENTENCES={
  te:  {jp:"コーヒーを飲んで、勉強します。", hi:"飲んで", en:"I drink coffee and (then) study."},
  ta:  {jp:"きのう映画を見た。", hi:"見た", en:"I watched a movie yesterday."},
  nai: {jp:"朝ごはんを食べない。", hi:"食べない", en:"I don't eat breakfast."},
  masu:{jp:"毎日日本語を勉強します。", hi:"勉強します", en:"I study Japanese every day."},
  tai: {jp:"日本に行きたいです。", hi:"行きたい", en:"I want to go to Japan."},
  pot: {jp:"私は漢字が読める。", hi:"読める", en:"I can read kanji."},
  vol: {jp:"一緒に帰ろう！", hi:"帰ろう", en:"Let's go home together!"},
  ba:  {jp:"急げば、間に合う。", hi:"急げば", en:"If we hurry, we'll make it in time."},
  tara:{jp:"家に着いたら、電話してください。", hi:"着いたら", en:"When you get home, please call me."},
  imp: {jp:"早く起きろ！", hi:"起きろ", en:"Get up already!"},
  pass:{jp:"先生に名前を呼ばれた。", hi:"呼ばれた", en:"My name was called by the teacher."},
  caus:{jp:"母は弟に野菜を食べさせた。", hi:"食べさせた", en:"Mom made my little brother eat vegetables."},
  aneg:{jp:"この店は高くない。", hi:"高くない", en:"This shop isn't expensive."},
  apast:{jp:"旅行はとても楽しかった。", hi:"楽しかった", en:"The trip was really fun."},
  apneg:{jp:"テストは難しくなかった。", hi:"難しくなかった", en:"The test wasn't difficult."},
  ate: {jp:"この部屋は広くて、明るい。", hi:"広くて", en:"This room is spacious and bright."},
  aadv:{jp:"毎朝早く起きます。", hi:"早く", en:"I get up early every morning."}
};
export const TYPE_LABEL={g:"godan・う-verb", i:"ichidan・る-verb", s:"irregular・する", k:"irregular・くる", ia:"い-adjective", na:"な-adjective"};
