export const FORMS=[
  {id:"te",  kind:"v", jp:"て形", en:"te-form", lvl:"N5",
   rule:"Godan: 〜う・つ・る → って ／ 〜む・ぶ・ぬ → んで ／ 〜く → いて ／ 〜ぐ → いで ／ 〜す → して\nIchidan: drop る → て\nする → して ／ くる → きて ／ ⚠ 行く → 行って"},
  {id:"ta",  kind:"v", jp:"た形", en:"plain past", lvl:"N5",
   rule:"Exactly the same sound changes as て形, with た／だ instead:\nって→った, んで→んだ, いて→いた, いで→いだ, して→した.\nIf you know て形, you know た形."},
  {id:"nai", kind:"v", jp:"ない形", en:"plain negative", lvl:"N5",
   rule:"Godan: change the last kana to the あ-row +ない (⚠ う → わ: 買う→買わない)\nIchidan: drop る + ない\nする → しない ／ くる → こない"},
  {id:"masu",kind:"v", jp:"ます形", en:"polite", lvl:"N5",
   rule:"Godan: change the last kana to the い-row + ます (飲む→飲みます)\nIchidan: drop る + ます\nする → します ／ くる → きます"},
  {id:"tai", kind:"v", jp:"たい形", en:"want to", lvl:"N5",
   rule:"Take the ます-stem and add たい.\n飲む→飲みたい ／ 食べる→食べたい ／ する→したい"},
  {id:"pot", kind:"v", jp:"可能形", en:"potential (can)", lvl:"N4",
   rule:"Godan: last kana to the え-row + る (飲む→飲める)\nIchidan: drop る + られる (⚠ 食べれる is the famous ら抜き mistake)\nする → できる ／ くる → こられる"},
  {id:"vol", kind:"v", jp:"意向形", en:"volitional (let's)", lvl:"N4",
   rule:"Godan: last kana to the お-row + う (飲む→飲もう)\nIchidan: drop る + よう\nする → しよう ／ くる → こよう"},
  {id:"ba",  kind:"v", jp:"ば形", en:"conditional 〜ば", lvl:"N4",
   rule:"Godan: last kana to the え-row + ば (飲む→飲めば)\nIchidan: drop る + れば\nする → すれば ／ くる → くれば"},
  {id:"tara",kind:"v", jp:"たら形", en:"conditional 〜たら", lvl:"N4",
   rule:"Just the た形 + ら. If you know た形, this is free.\n飲む→飲んだら ／ 食べる→食べたら ／ 行く→行ったら"},
  {id:"imp", kind:"v", jp:"命令形", en:"imperative", lvl:"N4",
   rule:"Godan: last kana to the え-row (飲む→飲め)\nIchidan: drop る + ろ (食べろ)\nする → しろ ／ くる → こい"},
  {id:"pass",kind:"v", jp:"受身形", en:"passive", lvl:"N4",
   rule:"Godan: last kana to the あ-row + れる (飲む→飲まれる)\nIchidan: drop る + られる (same as potential!)\nする → される ／ くる → こられる"},
  {id:"caus",kind:"v", jp:"使役形", en:"causative (make/let)", lvl:"N4",
   rule:"Godan: last kana to the あ-row + せる (飲む→飲ませる)\nIchidan: drop る + させる\nする → させる ／ くる → こさせる"},
  {id:"aneg", kind:"a", jp:"形容詞・否定", en:"adj negative", lvl:"N5",
   rule:"い-adj: drop い + くない (高い→高くない) ⚠ いい→よくない\nな-adj: + じゃない (静か→静かじゃない)\n⚠ きれい ends in い but is a な-adjective!"},
  {id:"apast",kind:"a", jp:"形容詞・過去", en:"adj past", lvl:"N5",
   rule:"い-adj: drop い + かった (高い→高かった) ⚠ いい→よかった\nな-adj: + だった (静か→静かだった)"},
  {id:"apneg",kind:"a", jp:"形容詞・過去否定", en:"adj past negative", lvl:"N5",
   rule:"い-adj: drop い + くなかった\nな-adj: + じゃなかった"},
  {id:"ate", kind:"a", jp:"形容詞・て形", en:"adj te-form (linking)", lvl:"N5",
   rule:"い-adj: drop い + くて (高くて安い = tall and cheap) ⚠ いい→よくて\nな-adj: + で (静かで便利 = quiet and convenient)"},
  {id:"aadv",kind:"a", jp:"副詞化", en:"adj → adverb", lvl:"N5", iaOnly:true,
   rule:"い-adj: drop い + く (早い→早く走る = run fast)\n(ない-adj use に: 静かに — not drilled here)"},
  {id:"dict", kind:"v", jp:"辞書形", en:"dictionary form", lvl:"N5",
   rule:"This is the plain, neutral form of the verb as found in a dictionary. No changes."},
  {id:"apres", kind:"a", jp:"形容詞・現在肯定", en:"adj present", lvl:"N5",
   rule:"Plain present affirmative adjective. No changes."}
];
export const FORM = Object.fromEntries(FORMS.map(f=>[f.id,f]));
export const SENTENCES={
  te:  {jp:"コーヒーを飲んで、勉強します。", hi:"飲んで", en:"I drink coffee and (then) study."},
  ta:  {jp:"きのう映画を見た。", hi:"見た", en:"I watched a movie yesterday."},
  nai: {jp:"朝ごはんを食べない。", hi:"食べない", en:"I don't eat breakfast."},
  masu:{jp:"毎日日本語を勉強します。", hi:"勉強します", en:"I study Japanese every day."},
  tai: {jp:"日本に行きたいです。", hi:"行きたい", en:"I want to go to Japan."},
  pot: {jp:"私は漢字が読める。", hi:"読める", en:"I can read kanji."},
  vol: {jp:"一緒に帰ろう！", hi:"帰ろう", en:"Let's go home together!"},
  ba:  {jp:"急げば、間に合う。", hi:"急げば", en:"If we hurry, we'll make it in time."},
  tara:{jp:"家に着いたら、電話してください。", hi:"着いたら", en:"When you get home, please call me."},
  imp: {jp:"早く起きろ！", hi:"起きろ", en:"Get up already!"},
  pass:{jp:"先生に名前を呼ばれた。", hi:"呼ばれた", en:"My name was called by the teacher."},
  caus:{jp:"母は弟に野菜を食べさせた。", hi:"食べさせた", en:"Mom made my little brother eat vegetables."},
  aneg:{jp:"この店は高くない。", hi:"高くない", en:"This shop isn't expensive."},
  apast:{jp:"旅行はとても楽しかった。", hi:"楽しかった", en:"The trip was really fun."},
  apneg:{jp:"テストは難しくなかった。", hi:"難しくなかった", en:"The test wasn't difficult."},
  ate: {jp:"この部屋は広くて、明るい。", hi:"広くて", en:"This room is spacious and bright."},
  aadv:{jp:"毎朝早く起きます。", hi:"早く", en:"I get up early every morning."}
};
export const TYPE_LABEL={g:"godan・う-verb", i:"ichidan・る-verb", s:"irregular・する", k:"irregular・くる", ia:"い-adjective", na:"な-adjective"};
