export const VERBS=[
  {k:"買う",r:"かう",m:"to buy",t:"g"},{k:"会う",r:"あう",m:"to meet",t:"g"},{k:"使う",r:"つかう",m:"to use",t:"g"},
  {k:"歌う",r:"うたう",m:"to sing",t:"g"},{k:"洗う",r:"あらう",m:"to wash",t:"g"},{k:"習う",r:"ならう",m:"to learn",t:"g"},
  {k:"行く",r:"いく",m:"to go",t:"g",x:1},{k:"書く",r:"かく",m:"to write",t:"g"},{k:"聞く",r:"きく",m:"to listen",t:"g"},
  {k:"歩く",r:"あるく",m:"to walk",t:"g"},{k:"働く",r:"はたらく",m:"to work",t:"g"},
  {k:"泳ぐ",r:"およぐ",m:"to swim",t:"g"},{k:"急ぐ",r:"いそぐ",m:"to hurry",t:"g"},{k:"脱ぐ",r:"ぬぐ",m:"to take off",t:"g"},
  {k:"話す",r:"はなす",m:"to speak",t:"g"},{k:"貸す",r:"かす",m:"to lend",t:"g"},{k:"消す",r:"けす",m:"to turn off",t:"g"},
  {k:"待つ",r:"まつ",m:"to wait",t:"g"},{k:"持つ",r:"もつ",m:"to hold",t:"g"},{k:"立つ",r:"たつ",m:"to stand",t:"g"},
  {k:"死ぬ",r:"しぬ",m:"to die",t:"g"},
  {k:"遊ぶ",r:"あそぶ",m:"to play",t:"g"},{k:"呼ぶ",r:"よぶ",m:"to call",t:"g"},{k:"飛ぶ",r:"とぶ",m:"to fly",t:"g"},
  {k:"飲む",r:"のむ",m:"to drink",t:"g"},{k:"読む",r:"よむ",m:"to read",t:"g"},{k:"休む",r:"やすむ",m:"to rest",t:"g"},
  {k:"住む",r:"すむ",m:"to live (in)",t:"g"},
  {k:"帰る",r:"かえる",m:"to go home ⚠godan",t:"g"},{k:"入る",r:"はいる",m:"to enter ⚠godan",t:"g"},
  {k:"走る",r:"はしる",m:"to run ⚠godan",t:"g"},{k:"知る",r:"しる",m:"to know ⚠godan",t:"g"},
  {k:"切る",r:"きる",m:"to cut ⚠godan",t:"g"},{k:"作る",r:"つくる",m:"to make",t:"g"},
  {k:"乗る",r:"のる",m:"to ride",t:"g"},{k:"取る",r:"とる",m:"to take",t:"g"},{k:"売る",r:"うる",m:"to sell",t:"g"},
  {k:"送る",r:"おくる",m:"to send",t:"g"},{k:"座る",r:"すわる",m:"to sit",t:"g"},
  {k:"食べる",r:"たべる",m:"to eat",t:"i"},{k:"見る",r:"みる",m:"to see",t:"i"},{k:"寝る",r:"ねる",m:"to sleep",t:"i"},
  {k:"起きる",r:"おきる",m:"to wake up",t:"i"},{k:"出る",r:"でる",m:"to leave",t:"i"},
  {k:"開ける",r:"あける",m:"to open",t:"i"},{k:"閉める",r:"しめる",m:"to close",t:"i"},
  {k:"教える",r:"おしえる",m:"to teach",t:"i"},{k:"覚える",r:"おぼえる",m:"to memorize",t:"i"},
  {k:"忘れる",r:"わすれる",m:"to forget",t:"i"},{k:"借りる",r:"かりる",m:"to borrow",t:"i"},
  {k:"着る",r:"きる",m:"to wear",t:"i"},{k:"降りる",r:"おりる",m:"to get off",t:"i"},{k:"浴びる",r:"あびる",m:"to shower",t:"i"},
  {k:"する",r:"する",m:"to do",t:"s"},{k:"勉強する",r:"べんきょうする",m:"to study",t:"s"},
  {k:"電話する",r:"でんわする",m:"to phone",t:"s"},{k:"掃除する",r:"そうじする",m:"to clean",t:"s"},
  {k:"練習する",r:"れんしゅうする",m:"to practice",t:"s"},{k:"来る",r:"くる",m:"to come",t:"k"},
  {k:"踊る",r:"おどる",m:"to dance",t:"g"},{k:"決める",r:"きめる",m:"to decide",t:"i"},
  {k:"守る",r:"まもる",m:"to protect",t:"g"},{k:"抱きしめる",r:"だきしめる",m:"to hug",t:"i"},
  {k:"妬む",r:"ねたむ",m:"to envy",t:"g"},{k:"従う",r:"したがう",m:"to obey",t:"g"},
  {k:"結ぶ",r:"むすぶ",m:"to tie",t:"g"},{k:"終わる",r:"おわる",m:"to end",t:"g"},
  {k:"壊す",r:"こわす",m:"to break",t:"g"},{k:"勝つ",r:"かつ",m:"to win",t:"g"},
  {k:"掴む",r:"つかむ",m:"to grab",t:"g"},{k:"縛る",r:"しばる",m:"to bind",t:"g"}
];
export const ADJS=[
  {k:"高い",r:"たかい",m:"tall / expensive",t:"ia"},{k:"安い",r:"やすい",m:"cheap",t:"ia"},
  {k:"大きい",r:"おおきい",m:"big",t:"ia"},{k:"小さい",r:"ちいさい",m:"small",t:"ia"},
  {k:"新しい",r:"あたらしい",m:"new",t:"ia"},{k:"古い",r:"ふるい",m:"old",t:"ia"},
  {k:"暑い",r:"あつい",m:"hot",t:"ia"},{k:"寒い",r:"さむい",m:"cold",t:"ia"},
  {k:"楽しい",r:"たのしい",m:"fun",t:"ia"},{k:"難しい",r:"むずかしい",m:"difficult",t:"ia"},
  {k:"忙しい",r:"いそがしい",m:"busy",t:"ia"},{k:"早い",r:"はやい",m:"early / fast",t:"ia"},
  {k:"近い",r:"ちかい",m:"near",t:"ia"},{k:"遠い",r:"とおい",m:"far",t:"ia"},
  {k:"おいしい",r:"おいしい",m:"delicious",t:"ia"},{k:"面白い",r:"おもしろい",m:"interesting",t:"ia"},
  {k:"いい",r:"いい",m:"good ⚠irregular",t:"ia"},
  {k:"元気",r:"げんき",m:"healthy / lively",t:"na"},{k:"静か",r:"しずか",m:"quiet",t:"na"},
  {k:"有名",r:"ゆうめい",m:"famous",t:"na"},{k:"便利",r:"べんり",m:"convenient",t:"na"},
  {k:"大変",r:"たいへん",m:"tough",t:"na"},{k:"好き",r:"すき",m:"liked",t:"na"},
  {k:"簡単",r:"かんたん",m:"simple",t:"na"},{k:"親切",r:"しんせつ",m:"kind",t:"na"},
  {k:"暇",r:"ひま",m:"free (time)",t:"na"},{k:"きれい",r:"きれい",m:"pretty / clean ⚠na-adj!",t:"na"},
  {k:"美しい",r:"うつくしい",m:"beautiful",t:"ia"},{k:"幼い",r:"おさない",m:"young",t:"ia"},
  {k:"優しい",r:"やさしい",m:"kind",t:"ia"},{k:"弱い",r:"よわい",m:"weak",t:"ia"}
];
