/**
 * Content for the Royal Gamble card table — the memory-matching game hosted
 * by the Gambler Prince. Pure data: lore, deck registry, tunables.
 */

export const CARDS_HOST = {
  name: "Prince Cassian",
  jp: "カシアン",
  title: "The Gambler Prince",
  tagline: "Third in line for the throne — first at every card table.",
  icon: "🃏",
  colors: { accent: "#E0B457", accent2: "#F5E3B8" },
  lines: {
    welcome: "Sit, apprentice. Words are my cards — and the table never lies.",
    deal: "A fresh deal. Memorize them well… I never repeat myself.",
    dealAgain: "More cards join the table. Keep up.",
    clear: "Cleared! You have quick eyes… for now.",
    allClear: "You matched every card I own?! …Double or nothing.",
    win: "The crown suits you tonight. Take your chips.",
    lose: "The house always wins, dear. Come back with sharper eyes.",
    notEnough: "You can't sit at my table with an empty hand — learn 5 cards first."
  }
};

/** Deck registry — data files generated by scripts/build_vocab.py into public/vocab/. */
export const CARD_DECKS = [
  { id: "starter", label: "Starter", sub: "A1" },
  { id: "elementary1", label: "Elementary 1", sub: "A2" },
  { id: "elementary2", label: "Elementary 2", sub: "A2" },
  { id: "preintermediate", label: "Pre-Intermediate", sub: "A2/B1" },
  { id: "intermediate1", label: "Intermediate 1", sub: "B1" },
  { id: "intermediate2", label: "Intermediate 2", sub: "B1" }
];

export const CARDS_BALANCE = {
  reviewBatch: 5,        // new cards dealt per learning round
  startPairs: 5,         // pairs on the table for the first round
  secondsPerPair: 3,     // timer budget per pair on the board
  chipsPerMatch: 1,      // royal chips earned per matched pair
  lowTimeMs: 3500,       // warning ticks below this
  srs: {
    matchedClean: -1,    // matched without a fumble → appears less (floor -10)
    matchedSloppy: +3,   // matched after mismatching → appears more
    leftOnTable: +2,     // time ran out with the card unmatched
    notInRound: +2,      // waiting in the deck
    floor: -10
  }
};
